# Generated by Django 5.2.6 on 2025-09-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analyst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField()),
                ('context_analyst', models.TextField()),
                ('save_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
