# Generated by Django 5.2.6 on 2025-09-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlings', '0002_analyst'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField()),
                ('status', models.CharField(choices=[('PENDING', '대기'), ('IN_PROGRESS', '진행중'), ('COMPLETED', '완료'), ('FAILED', '실패')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
