# Generated by Django 5.2.6 on 2025-09-27 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawlings', '0003_crawltask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawltask',
            name='company_name',
        ),
    ]
