# Generated by Django 5.2.6 on 2025-09-27 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawlings', '0004_remove_crawltask_company_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CrawlTask',
        ),
    ]
