# Generated by Django 5.2.6 on 2025-09-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlings', '0002_analyst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='company_code',
            field=models.CharField(max_length=7),
        ),
    ]
