# Generated by Django 5.2.6 on 2025-09-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bakery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('rating', models.FloatField()),
                ('opening_time', models.DateTimeField()),
                ('closing_time', models.DateTimeField()),
            ],
        ),
    ]
