# Generated by Django 5.2.6 on 2025-09-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=15)),
                ('content', models.TextField()),
                ('post_time', models.DateTimeField()),
                ('ttabong', models.IntegerField()),
                ('ZZal', models.CharField(blank=True, null=True)),
                ('company_name', models.CharField()),
                ('company_code', models.IntegerField()),
            ],
        ),
    ]
